
"""practiceQuestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvUzMW-H2-K9xuhtW44dPnLGDEEMiDgk
"""
# pyramid pattern

for i in range(5):
  for j in range(5-1-i):
    print(" " ,end='')
  for j in range (2*i+1):
      print("*",end='')
  print()

# Hollow Square Pattern

n=5
print("*" * n)
for i in range(n - 2):
    print("*" + " " * (n-2) + "*")
print("*" * n)


# Stair Pattern
for i in range(5):
  for j in range (i+1):
    print("*",end='')
  print()

# Reverse Stair Pattern
for i in range(15):
  for j in range (15-i):
    print("*",end = '')
  print()



#  program to check palindrome
a = input("enter name ")
for i in range (len(a)):
  b= b+ a[len(a)-1-i]
if(a==b):
  print("String is Palindrome")
else :
  print("string is not Palindrome")


# count the blank spaces.
count = 0
a =str(input("enter a string "))
for i in range (len(a)):
  if(a[i] == " "):
    count= count + 1
print("number of blank spaces " ,count)


# Reversing a String 
a =str(input("enter a string "))
for i in range (len(a)):
  print(a[len(a)-i-1],end='')


# count no. of vowels and print all the vowels
vowelCount = 0
s = str(input("enter a string "))
for i in range(len(s)):
  if (s[i] == 'a') or (s[i] == 'e') or (s[i] == 'i') or (s[i] == 'o') or (s[i] == 'u') or (s[i] == 'A') or (s[i] == 'E') or (s[i] == 'I') or (s[i] == 'O') or (s[i] == 'U'):
      vowelCount = vowelCount +1
      print(s[i] ,end =' ')
print()
print("vowel Count " , vowelCount)
